export const defaultUser = {
  id: null,
  aktiv: true,
  registrierungsdatum: '',
  bezahlt: false,
  schulkind: false,
  vorname: '',
  nachname: '',
  geburtsdatum: '',
  strasse: '',
  hausnummer: '',
  wohnort: '',
  postleitzahl: '',
  telefon: '',
  email: '',
  darfErmaessigtenPreisZahlen: false,
  darfBehandeltWerden: null,
  darfAlleinNachHause: null,
  darfReiten: null,
  darfSchwimmen: null,
  schwimmAbzeichen: '',
  allergien: '',
  medikamente: '',
  krankheiten: '',
  hitzeempfindlich: false,
  krankenkasse: '',
  essenVegetarier: false,
  essenLaktoseUnvertraeglichkeit: false,
  essenEierUnvertraeglichkeit: false,
  essenWeitereLimitierungen: '',
  liegtBehinderungVor: false,
  notfallKontakt: {
    id: null,
    name: '',
    anschrift: '',
    telefon: '',
  },
  arzt: {
    id: null,
    name: '',
    anschrift: '',
    telefon: '',
  },
  behinderung: {
    id: null,
    merkzeichen_AussergewoehnlicheGehbehinderung_aG: false,
    merkzeichen_Hilflosigkeit_H: false,
    merkzeichen_Blind_Bl: false,
    merkzeichen_Gehoerlos_Gl: false,
    merkzeichen_BerechtigtZurMitnahmeEinerBegleitperson_B: false,
    merkzeichen_BeeintraechtigungImStrassenverkehr_G: false,
    merkzeichen_Taubblind_TBL: false,
    rollstuhlNutzungNotwendig: false,
    weitereHilfsmittel: '',
    wertmarkeVorhanden: false,
    begleitungNotwendig: false,
    begleitpersonPflege: false,
    begleitpersonMedizinischeVersorgung: false,
    begleitpersonMobilitaet: false,
    begleitpersonOrientierung: false,
    begleitpersonSozialeBegleitung: false,
    begleitpersonSinneswahrnehmung: false,
    eingeschraenkteSinne: '',
    hinweiseZumUmgangMitDemKind: '',
    unterstuetzungSucheBegleitperson: false,
    gewohnterBegleitpersonenDienstleister: '',
    beantragungKostenuebernahmeBegleitperson: false,
    zustimmungWeitergabeDatenAmtFamilieUndSoziales: false,
  },
  datenschutzErklaerungAkzeptiert: false,
  teilnahmeBedingungAkzeptiert: false,
};

export const defaultProject = {
  id: null,
  name: '',
  datumBeginn: '',
  datumEnde: '',
  plaetzeGesamt: '',
  plaetzeReserviert: '',
  plaetzeFrei: '',
  plaetzeBelegt: '',
  mindestAlter: '',
  hoechstAlter: '',
};
