# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress -DskipTests package

      - name: Test with Maven
        run: mvn --batch-mode --no-transfer-progress verify

      - uses: codecov/codecov-action@v1
        with:
          file: ./backend/target/site/jacoco/jacoco.xml
          name: codecov